export enum ExampleOperationName {
  SETUP_BASIC_AUTH = 'EXAMPLE/SETUP_BASIC_AUTH',
  USER_BY_ID = 'EXAMPLE/USER/BY_ID',
  USER_SEARCH = 'EXAMPLE/USER/SEARCH',
  USER_CREATE = 'EXAMPLE/USER/CREATE',
  USER_UPDATE = 'EXAMPLE/USER/UPDATE'
}
